/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomenclature;

import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.Scanner;
import javax.swing.JTextField;

/**
 *
 * @author phili
 */
public class PracticeGameWindow extends javax.swing.JFrame {
    
    Scanner scan = new Scanner(System.in);
    
    private String prevQues;
    private String prevAns;
    private String corAns;
    
    URL iconImage = this.getClass().getClassLoader().getResource("NomenclaturePics/TaskbarIcon.png");
    /**
     * Creates new form PracticeGameWindow
     */
    public PracticeGameWindow() {
        initComponents();
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(iconImage));
        
        TheGame.databaseAccess(String.valueOf(databaseCombo.getSelectedItem()).toLowerCase());
        if(TheGame.displayChoice())
        {
            questionLabel.setText(TheGame.formula);
        }
        else
        {
            questionLabel.setText(TheGame.name);
        }
        
        toSubscript(answerField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreLabel = new javax.swing.JLabel();
        rightLabel = new javax.swing.JLabel();
        rightScore = new javax.swing.JLabel();
        wrongLabel = new javax.swing.JLabel();
        wrongScore = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalScore = new javax.swing.JLabel();
        databaseCombo = new javax.swing.JComboBox<>();
        questionLabel = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        comboBoxLabel = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        prevQuesLabel = new javax.swing.JLabel();
        actualPrevQues = new javax.swing.JLabel();
        actualPrevAns = new javax.swing.JLabel();
        prevAnsLabel = new javax.swing.JLabel();
        actualCorAns = new javax.swing.JLabel();
        corAnsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practice");
        setResizable(false);

        scoreLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        scoreLabel.setText("Score:");

        rightLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        rightLabel.setForeground(new java.awt.Color(51, 102, 0));
        rightLabel.setText("Right:");

        rightScore.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        rightScore.setForeground(new java.awt.Color(51, 102, 0));
        rightScore.setText("0");

        wrongLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        wrongLabel.setForeground(new java.awt.Color(153, 0, 0));
        wrongLabel.setText("Wrong:");

        wrongScore.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        wrongScore.setForeground(new java.awt.Color(153, 0, 0));
        wrongScore.setText("0");

        totalLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        totalLabel.setText("Total:");

        totalScore.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        totalScore.setText("0");

        databaseCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        databaseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anions", "Cations", "Acids", "Ionic", "Covalent" }));
        databaseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseComboActionPerformed(evt);
            }
        });

        questionLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("Question");

        answerField.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        answerField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFieldActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        comboBoxLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        comboBoxLabel.setText("Nomenclature Tables:");

        instructionsLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        instructionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionsLabel.setText("<html><b>Instructions</b>: If the <b>Chemical Name</b> is displayed, type in the <b> Chemical Formula</b>. <br>\n<p style = \"margin-left: 49px\"> If the <b>Chemical Formula</b> is displayed, type in the <b>Chemical Name</b>. </html>");

        prevQuesLabel.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        prevQuesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevQuesLabel.setText("Previous Question:");

        actualPrevQues.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        actualPrevQues.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualPrevQues.setText("Previous Question...");

        actualPrevAns.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        actualPrevAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualPrevAns.setText("Previous Answer...");

        prevAnsLabel.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        prevAnsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevAnsLabel.setText("Previous Answer:");

        actualCorAns.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        actualCorAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualCorAns.setText("Correct Answer...");

        corAnsLabel.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        corAnsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        corAnsLabel.setText("Correct Answer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(scoreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(rightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightScore, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrongLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrongScore, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalScore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(databaseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(actualPrevQues, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(actualPrevAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prevQuesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prevAnsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(corAnsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(actualCorAns, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instructionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightLabel)
                    .addComponent(rightScore)
                    .addComponent(wrongLabel)
                    .addComponent(wrongScore)
                    .addComponent(totalLabel)
                    .addComponent(totalScore))
                .addGap(18, 18, 18)
                .addComponent(instructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(prevQuesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualPrevQues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corAnsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualCorAns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prevAnsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualPrevAns)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void databaseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseComboActionPerformed
        TheGame.databaseAccess(String.valueOf(databaseCombo.getSelectedItem()).toLowerCase());
        if(TheGame.displayChoice())
        {
            questionLabel.setText(TheGame.formula);
        }
        else
        {
            questionLabel.setText(TheGame.name);
        }
    }//GEN-LAST:event_databaseComboActionPerformed

    private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed

    }//GEN-LAST:event_answerFieldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String text = answerField.getText();
        String right = rightScore.getText();
        String wrong = wrongScore.getText();
        String total = totalScore.getText();
        
        if(TheGame.name.equals(text) || TheGame.formula.equals(text))
        {
            right = String.valueOf(Integer.parseInt(right) + 1);
            total = String.valueOf(Integer.parseInt(total) + 1);
        }
        else
        {
            wrong = String.valueOf(Integer.parseInt(wrong) + 1);
            total = String.valueOf(Integer.parseInt(total) + 1);
        }
        
        rightScore.setText(right);
        wrongScore.setText(wrong);
        totalScore.setText(total);
        answerField.setText("");
        TheGame.databaseAccess(String.valueOf(databaseCombo.getSelectedItem()).toLowerCase());
        if(TheGame.displayChoice())
        {
            questionLabel.setText(TheGame.formula);
        }
        else
        {
            questionLabel.setText(TheGame.name);
        }        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private static void toSubscript(JTextField text)
    {
        text.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                JTextField textField = (JTextField) e.getSource();
                String string1 = textField.getText();
                textField.setText(SubScriptFinder.changer2(string1));
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticeGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticeGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticeGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticeGameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticeGameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualCorAns;
    private javax.swing.JLabel actualPrevAns;
    private javax.swing.JLabel actualPrevQues;
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel comboBoxLabel;
    private javax.swing.JLabel corAnsLabel;
    private javax.swing.JComboBox<String> databaseCombo;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JLabel prevAnsLabel;
    private javax.swing.JLabel prevQuesLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel rightLabel;
    private javax.swing.JLabel rightScore;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalScore;
    private javax.swing.JLabel wrongLabel;
    private javax.swing.JLabel wrongScore;
    // End of variables declaration//GEN-END:variables
}
